path-properties:
  base-path: /tmp
  resume: false
  multithread: false
  compare-way-around: false
  lov-url: http://lov.okfn.org/lov.nq.gz
  resume-errors: false
  nr-threads: 2
  remove-dataset-pass: 12345

spring:
  data:
    mongodb:
      host: 192.168.0.16
      username: ciro5
      password: ciro5
      database: ciro
#      authentication-database: ciro
      
      